### ISSUE TITLE
Vertically center the login box (ReactJS)

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/react-mern-app#1]
Make the login box both horizontal and vertically centered in the file client/src/pages/login.js

**Comment by taloncjones** [comment]
Hi @priyanshbalyan,
Is this issue being worked on?

**Comment by priyanshbalyan** [comment]
> Hi @priyanshbalyan,
> Is this issue being worked on?
Nope! It's up for grabs for new comers. Feel free to submit a PR.
