### ISSUE TITLE
Fix back-end crashing if mongoDB not found in system

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/react-mern-app#11]
Currently the back-end crashes if mongoDB is not found in the system or no .env file is present. Fix the crash and display an appropriate error message as such in the console.

You can just run the backend with ``npm run backend``

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says ``Fixes #11``

Steps for completing the task:

1.   Fork the repo
2.   Make your necessary changes.
3.   Submit a PR

Leave a star if you like the project!

**Comment by tonythetiger323** [comment]
I would like to handle this!

**Comment by priyanshbalyan** [comment]
@tonythetiger323 Go right ahead!

**Comment by priyanshbalyan** [comment]
@tonythetiger323 Hey are you still working on the issue?

**Comment by iAmmar7** [comment]
Can i work on this issue? I haven't done any open-source contribution before.

**Comment by priyanshbalyan** [comment]
@iAmmar7 Sure! Feel free to submit a PR.

**Comment by tonythetiger323** [comment]
My apologies, when IL got put under a shelter in place order I made a quick decision to stay with some friends for awhile and have been away from my desktop, I should have let you know sooner but got distracted with all that’s going on.

**Comment by priyanshbalyan** [comment]
@tonythetiger323 Sorry it's been a quite a number of days since there was any activity so I reassigned the issue to a different person. You can work on other active issues in the project. Hope you understand.
