### ISSUE TITLE
Nodemon is not listed as dependency in package.json

### ISSUE THREAD

**Issue by tonythetiger323** [priyanshbalyan/react-mern-app#12]
Attempts to run npm run backend fail and return an error that Nodemon is not installed. Upon review of package.json Nodemon is not listed as neither a dependency nor a dev dependency.
Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #<issue-number>

Steps for completing the task:

1.   Fork the repo
2.   Make your necessary changes.
3.   Submit a PR

Leave a star if you like the project!

Note: I will handle this issue myself as its needed to resolve issue #11 which I have started working on.

**Comment by tonythetiger323** [comment]
Sweet, thanks! My apologies for making a little more work for you by creating this issue.

**Comment by priyanshbalyan** [comment]
No problem!
