### ISSUE TITLE
Remove toolbar from login page

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/react-mern-app#15]
Remove the toolbar from login page. The toolbar should appear when user has logged in.

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #15

Steps for completing the task:

1.   Fork the repo
2.   Make your necessary changes.
3.   Submit a PR

Leave a star if you like the project!

**Comment by szechla** [comment]
Hi, I can handle this.

**Comment by priyanshbalyan** [comment]
@szechla Go right ahead!
