### ISSUE TITLE
Improve the login user interface

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/react-mern-app#7]
Currently the UI doesn't look as good as a login UI should look. Improve the login UI. You can use any library as needed for the completion of this task.
You can take inspirations for the login UI from here - https://dribbble.com/tags/login_screen

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #7

Steps for completing the task:
1. Fork the repo
2. Make your necessary changes.
3. Submit a PR

Leave a star if you like the project!

**Comment by yonis9** [comment]
Hi, I working on it

**Comment by priyanshbalyan** [comment]
@yonis9 Great!
