### ISSUE TITLE
Add front-end test cases

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/react-mern-app#8]
Add front-end test cases to the project. You can take help from how the back-end test cases are implemented. The tests should be run with the same script as back-end i.e. ``npm run test``

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #8

Steps for completing the task:

1.   Fork the repo
2.   Make your necessary changes.
3.   Submit a PR

Leave a star if you like the project!

**Comment by subodhss23** [comment]
Hey, can I work on it?

**Comment by priyanshbalyan** [comment]
@subodhss23 Go right ahead!

**Comment by subodhss23** [comment]
@priyanshbalyan do I use jest?? do you have any specific preference you want me to follow? I am fairly new, if you have any resources that might help, please pass this way.

**Comment by priyanshbalyan** [comment]
@subodhss23 Jest would be preferrable, but to make the task easier I'm not putting any restriction on it. You can use any testing library as you prefer. A good resource would be https://jestjs.io/docs/en/tutorial-react

**Comment by priyanshbalyan** [comment]
@subodhss23 Hey are you still working on the issue?

**Comment by subodhss23** [comment]
Sorry no.
